### ISSUE TITLE
Make ansible role compatible with OpenLDAP 2.5

### ISSUE THREAD

**Issue by Aditya-DP** [ltb-project/ansible-role-ldaptoolbox-openldap#16]
Hi team,

Just wanted to know if there are any plans to create a tag for openldap25 with latest changes i.e. till commit 695a689ff91a83b47fbc6f575be37e1f811bd719.

Current tag doesn't seem to cover changes from later commits.

**Comment by davidcoutadeur** [comment]
Hello,

Could be interesting, indeed.

However, since then, there are also improvements in the recipe that are not related to openldap26

Maybe we can also provide a default config file for OpenLDAP 2.5 and explain how to modify the repo link to continue using 2.5

Self-reminder: meanwhile, also add a flag for enabling / disabling certificate deployment

**Comment by Aditya-DP** [comment]
Thanks @davidcoutadeur 

Any inputs will be very helpful as we were using ltb for openldap2.5 through main branch but due to recent changes everything started failing. 

Hence thought of bringing up the question for any possible builds specific for openldap2.5

**Comment by davidcoutadeur** [comment]
@Aditya-DP I have made a new PR for making this recipe compatible with OpenLDAP 2.5.

You can check new variable `ldaptoolbox_openldap_version: "2.6"`
